### PR TITLE
New Causal-LWW Register

### PR DESCRIPTION
**Pull request by lenary**
Based on dvvset.erl from https://github.com/ricardobcl/Dotted-Version-Vectors

Looking for feedback, and maybe help from someone to make the crdt_statem_eqc test for this, which I'm slightly lost by.

Also, waiting to hear back on whether or not I can even include dvvset.erl (due to licencing issues)

### CODE REVIEW

**Comment by russelldb** [comment]
Finally picking this up now. Can only apologise for the huge delay.

**Comment by lenary** [comment]
Well, I'm around enough to answer questions if you need me to :)

**Comment by tsantero** [comment]
Is there anything I can do to help expedite getting this PR merged?

**Comment by tsantero** [comment]
it turns out the last write did not win afterall

**Comment by lenary** [comment]
please can the last writer switch the light out on their way out

**Pull request closed without merging**
