### PR TITLE
Use a binary uuid for actor id

### PR DESCRIPTION
**Pull request by russelldb**
I tried with both druuid and uuid and in my (micro) benchmark the pure erlang uuid.erl module was faster, so I went with that. _HOWEVER_ we'd better check about the legal status of that licence header from Travis Vachon. 

Speed is probably not _really_ an issue, since at this point we are only talking about uuids for vnodeids. But, if we start using them for U-Sets then maybe speed matters.

Let's talk.

### CODE REVIEW

**Comment by seancribbs** [comment]
That license reads like the MIT or BSD license. Note that the `-import(random).` directive has no effect since it doesn't import any functions.

**Comment by seancribbs** [comment]
Can you share your benchmarks? I'd love to see the comparison.

**Comment by russelldb** [comment]
Heh, 'benchmarks' is timer:tc a few thousand times. But given the infrequency of use, maybe druuid makes more sense for the license alone.

**Comment by seancribbs** [comment]
@russelldb Yes, this looks to be http://opensource.org/licenses/BSD-3-Clause. I'm ok with inclusion as long as no other deps have a uuid generator that we can reuse. Also, as you say, setting it on startup is relatively infrequent and not in the path of normal operations.

The rest of this is so simple, :+1: to merge.

**Comment by russelldb** [comment]
Going to merge it, and add concern about license as an issue. Maybe just check with Dizzy/Jon/Justin at a later date before we ship/flip the bit.

**Pull request merged**
