### PR TITLE
Add README to riak_dt

### PR DESCRIPTION
**Pull request by russelldb**
If we are going to open source we need at least a cursory README in the repo.

### CODE REVIEW

**Comment by PharkMillups** [comment]
Good stuff. A few nit-picky grammar/markup things:

> Built on riak core and deployed with riak.

It's built on riak core and deployed with riak. 

> All our current work is around supporting fast, replicated, eventually consistent counters (though more data types are in the repo, and on the way.)

All of our current work is around supporting fast, replicated, eventually consistent counters (though more data types are in the repo, and on the way).  

> This work is based on the paper "A Comprehensive study of Convergent and Commutative Replicated Data Types". which you may find an interesting read.

This work is based on the paper - A Comprehensive study of Convergent and Commutative Replicated Data Type -  which you may find an interesting read.

> Which should have fetched all the riak dependancies from github and compiled them, and create 4 release directories under the dev directory. Now start your nodes and build your cluster.

Ths should have fetched all the riak dependancies from github, compiled them, and created four release directories under the `dev` directory. 

Now start your nodes and build your cluster.

> There is no explicit create operation for a counter

There is no explicit `create` operation for a counter

> You can decrement a counter too:

You can decrement a counter, too:

**Comment by russelldb** [comment]
Added a commit which incorporates your suggestions. Please to be re-reviewing.

**Comment by seancribbs** [comment]
:+1: assuming @PharkMillups likes it.

**Comment by PharkMillups** [comment]
Phark approves. Phark will permit merge.

**Pull request merged**
