### PR TITLE
riak_dt_oe_flag is broken the same was od_flag was

### PR DESCRIPTION
**Pull request by lenary**
cc @lenary we need to fix oe_flag.

### CODE REVIEW

**Comment by lenary** [comment]
Yeah, I'll try fix it now, PR soonish.

**Comment by seancribbs** [comment]
Assigned 2.0.1 milestone. Not critical for release, but should be fixed before we forget about it.

**Comment by lenary** [comment]
I'm running into a problem trying to use dialyzer on this: https://gist.github.com/lenary/8238f2aef9419beade14

Eunits and xref seem to pass.

**Comment by lenary** [comment]
Now up-to-date with develop. Dialyzes, xrefs, eunits are all successful.

Ready for Review (but not urgent)

**Pull request closed without merging**
