### PR TITLE
Build improvements.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
@seancribbs @russelldb 

Resolve a series of Dialyzer errors, add rebar, and add a Makefile.
Also update dependencies to latest Bitcask and Riak Core.

### CODE REVIEW

**Comment by seancribbs** [comment]
:+1:

**Comment by cmeiklejohn** [comment]
Word, thanks.

**Comment by seancribbs** [comment]
FYI this is still (and will remain) a prototype.

**Comment by cmeiklejohn** [comment]
Ah, good to know.

**Pull request merged**
