### PR TITLE
sets->to->ordsets [JIRA: RIAK-2385]

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
…cross datatypes (orswot, od_flag, map) for small perf gain.

Benchmark posts added to thread. Driver used is in PR https://github.com/basho/basho_bench/tree/new_driver/zl/riak_dt-driver-start-with-sets. 

Please review @russelldb!

### CODE REVIEW

**Comment by russelldb** [comment]
Tests all pass. Cover shows the changed lines are run many times (thanks quickcheck!) All looks good to me. Once some info on perf improvement is added I'll Plus One. Thanks!

**Comment by kmarekspartz** [comment]
If I get a chance, I'll re-run these against this branch: http://kyle.marek-spartz.org/posts/2014-12-01-benchmarking-large-riak-data-types.html

**Comment by zeeshanlakhani** [comment]
Graphs/discussion y'all (again, **pretty minor improvements**, but improvements nonetheless)... more tracing after the rest of the benching needs are done and 2.2 is out:

## sets~single~insert~10@500x1000e~50c~3m~bitcask

For sets themselves, things mostly stayed the same, but single-set comparisons (no distribution of key PUTs) showcased improved latencies:

### w/o change

sets single insert 10 500x1000e 50c 3m bitcask

### w/change

## sets single insert 10 500x1000e 50c 3m bitcask

## sets~insert~500x1000ex10sets~55c~20m~leveldb

And we see something similar w/ a larger, .5 megabyte object:

### w/o change

sets insert 500x1000ex10sets 55c 20m leveldb

### w/ change

## sets insert 500x1000ex10sets 55c 20m leveldb

## maps~counter^insert@20~register^modify@2~read@1~flag^modify@1~4@1000bx1000e~10keys~60c~15m~bitcask

For the _map_, we see latencies average a lower-rate w/ complex  maps (containing multiple types):

### w/o change

baseline_maps counter insert 20 register modify 2 read 1 flag modify 1 4 1000bx1000e 10keys 60c 15m bitcask

### w/ change

## _maps counter insert 20 register modify 2 read 1 flag modify 1 4 1000bx1000e 10keys 60c 15m bitcask

## maps~set^modify@10~set^remove@1~multiops^insert@5~4@100b~1000e~10000keys~75c~15m~leveldb

And a wee-bit better throughput on average:

### w/o change

baseline_maps set modify 10 set remove 1 multiops insert 5 4 100b 1000e 10000keys 75c 15m leveldb

### w/ change

## _maps set modify 10 set remove 1 multiops insert 5 4 100b 1000e 10000keys 75c 15m leveldb

## maps~single~counter^insert@1~set^modify@3~read@5~set^remove@1~multiops^insert@1~10000seqint~25c~8m~bitcask

And, as w/ single-sets above, we can notice that even though we still increase in linear time (wrt latencies), the overall slope of the `ordsets` runs are better overall, especially w/ multi-op maps:

### w/o change

baseline_maps single counter insert 1 set modify 3 read 5 set remove 1 multiops insert 1 10000seqint 25c 8m bitcask

### w/ change

_maps single counter insert 1 set modify 3 read 5 set remove 1 multiops insert 1 10000seqint 25c 8m bitcask

**Comment by zeeshanlakhani** [comment]
@zeckalpha thanks! I just added up some of the bench graphs. Yeah, it's pretty minor, but we also don't see worse perf w/ maps, as I was worried about this [check](https://github.com/basho/riak_dt/pull/117/files#diff-02181c55b60086bdf51f13c5000060d4R544). Also, the b_b driver used is here: https://github.com/basho/basho_bench/tree/new_driver/zl/riak_dt-driver-start-with-sets... over protocol buffers (and the erlang-client).

**Comment by kmarekspartz** [comment]
Neat!

**Comment by russelldb** [comment]
+1 37a3bb335391efa50e26305458024d3d8421e1ab

Nice! very thorough. Thanks @zeeshanlakhani

**Comment by zeeshanlakhani** [comment]
create jira issue

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Pull request merged**
