### PR TITLE
More Flag CRDTs

### PR DESCRIPTION
**Pull request by lenary**
This time some OE-/OD-flags, which work like a single-element OR-Set.

Much more useful, eh?
- OD-Flag has an enable bias, starts `off`.
- OE-Flag has a disable bias, starts `on`.

### CODE REVIEW

**Comment by lenary** [comment]
@seancribbs this branch can be merged into multi_crdt methinks (which will pull in the rest of the flags too)

**Comment by seancribbs** [comment]
@lenary Yep.

**Comment by lenary** [comment]
@seancribbs seems I'll have to do the merge manually. Should only take a moment for me to do.

**Comment by lenary** [comment]
Merged in 7ff3da66554cb66c470d7218631f059463c30a9d (but git hates me tonight, so it's just right there.)

**Pull request closed without merging**
