### PR TITLE
Move all version / tag information to a single location

### PR DESCRIPTION
**Pull request by lenary**
Currently the to/from binary stuff is per file, the macros for version / tag should be in a single location, if just because adding a new one means looking in every file.

riak_dt.hrl seems like the logical place.

maybe a macro like ?TAG(?MODULE) would do it?

### CODE REVIEW

**Comment by lenary** [comment]
Mine!

**Comment by russelldb** [comment]
Utterly fantastic! Thanks. (+1 from me)

**Comment by lenary** [comment]
Ok, I added a little more docs. Going to mandate that new tags are checked out of the 90+ range, and should be at least tried to be kept organised...

**Comment by seancribbs** [comment]
Yeah, let's merge this.

**Comment by russelldb** [comment]
make test/dialyzer/xref all pass. Many thanks @lenary, much need, good work!

**Pull request merged**
