### PR TITLE
Edoc cleanup

### PR DESCRIPTION
**Pull request by macintux**
- Lots of `@see` fixes
- UTF-8 for Nuno's name rendering
- URL tweaks
- Other minor formatting issues

### CODE REVIEW

**Comment by lenary** [comment]
Looks good to me, but someone else should +1. The build fail is because the builder doesn't have EQC, something I raised in tools, but needs to wait for jared to get back to solve (i believe)

**Comment by russelldb** [comment]
+1  c82bab8

**Comment by slfritchie** [comment]
+1

**Comment by slfritchie** [comment]
+1 515c09c

**Comment by russelldb** [comment]
@borshop merge

**Comment by russelldb** [comment]
Thanks @macintux

**Pull request merged**
