### PR TITLE
Support negative counter increments and decrements

### PR DESCRIPTION
**Pull request by lenary**
Apparently a boog in emcounter. Fixed, so server-side should have no errors with any integers and any of `increment` and `decrement`.

### CODE REVIEW

**Comment by russelldb** [comment]
How do I test this? Please provide the steps that provoke the bug this fixes, so I can verify. Also, a _test_ that shows the bug and the fix would be very valuable (be it a riak_test, or a local unit test)

**Comment by macintux** [comment]
I don't think this is entirely correct: IIRC from looking at this code yesterday the Erlang specs indicate positive integers only, so that will have to be tweaked (although buildbot didn't gripe about Dialyzer).

I also suspected this should be handled one layer higher in the stack, but haven't looked to see where that would be.

Testing should be easy: fire up the Erlang client and send a single decrement. That should crash a node IIRC.

Will look more in a bit.

Thanks @lenary, really appreciate you getting this started.

**Comment by lenary** [comment]
@russelldb there's a new eunit test in 9109d7e

**Comment by russelldb** [comment]
Thanks @lenary this all works fine now

+1 9109d7e

**Comment by macintux** [comment]
I assume we need to fix the specs before merging

**Comment by macintux** [comment]
@borshop merge

**Pull request merged**
