### PR TITLE
Fix semantics of counters resource

### PR DESCRIPTION
**Pull request by seancribbs**
The current counters increment and decrement like so:

```
POST /counters/a/increment
POST /counters/a/decrement
```

This is a bad practice as it puts the verb in the URL. It would be better to use form parameters or JSON to submit the "change". curl examples:

``` bash
curl http://riakhost:8098/counters/a -F increment=5
curl http://riakhost:8098/counters/a -F decrement=2
curl http://riakhost:8098/counters/a -d '{"increment":5}' -H "Content-Type: application/json"
```

### CODE REVIEW

**Comment by russelldb** [comment]
Is it possible that the README could be updated to reflect this change, too, please?

**Comment by seancribbs** [comment]
Will do.

Sean Cribbs

**Comment by seancribbs** [comment]
@russelldb Fixed the examples. Travis build is failing, but could you run the WM tests locally?

**Comment by russelldb** [comment]
Hmm, test times out for me locally. Will dig a little.

**Comment by seancribbs** [comment]
@russelldb This may be similar to the timeouts I would occasionally see testing riak_api. I'll find out what I did there and possibly include an additional wait.

**Comment by seancribbs** [comment]
@russelldb I found the culprit, the vnode test wasn't calling `meck:unload()` at the end of a test with mocks installed. This broke the vnode, making it impossible to send a request to any of them. Now it works and plows through the tests quickly.

**Comment by russelldb** [comment]
Works for me. Many thanks +1.

**Pull request merged**
