### PR TITLE
Make sure all data types use configured compression in t2b/b2t

### PR DESCRIPTION
**Pull request by lenary**
For 2.0 release (map and orswot currently use compression):
- [x] lwwreg (only ever in map, which never calls to_binary/1 in lwwreg)
- [x] od-flag (only ever in map, which never calls to_binary/1 in od-flag)
- [x] pn-counter (we've kinda looked at this, but compression might do better)

For later:
- [ ] gcounter
- [ ] gset
- [ ] oe-flag
- [ ] orset

### CODE REVIEW

**Comment by seancribbs** [comment]
`riak_dt_orswot` uses the compression setting incorrectly. We should wrap the setting in a centralized function so as to reduce copy-pasta.

**Comment by lenary** [comment]
Going to attack this now, because bored in a class.

**Comment by lenary** [comment]
lww-reg and pn-counter will be incompatible with current representations if we use the centralised functions. 

What's the status of breaking changes right now?

**Comment by russelldb** [comment]
Status is "do it!" https://www.youtube.com/watch?v=M9-IZ1pNk00

**Comment by lenary** [comment]
Actually, after a closer reading, not going to be incompatible for pncounter V2 serialisation (which is the one we aim to upgrade to anyway).

**Comment by seancribbs** [comment]
:+1: 786008f

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
