### PR TITLE
Add xref target

### PR DESCRIPTION
**Pull request by Vagabond**

### CODE REVIEW

**Comment by russelldb** [comment]
I like you understated, spare, efficient, no-effort-wasted style. But for posterities sake, any kind of explanation as to what this is for, what good it does, and how to run it would just be really nice.

"Please merge this xref change 'cos the tools team think it will make your code better, xref will find bugs because it does…you can run it like…"

I appreciate the faith in my knowledge that this empty PR has, but really, I had to go and look up xref to figure out what you'd done and why.

**Comment by russelldb** [comment]
All that aside. Ran it. It reports no issues. I assume this mean it works and all is good. +1 to merge.

**Comment by Vagabond** [comment]
Yes, sorry. This is part of an effort to add meaningful xref targets to all our repos, so if we have another issue where an incomplete backport or a typo introduces a function call to an undefined function, we have some kind of a warning. It was mostly intended for @reiddraper to review, as we've been doing a series of them.

**Comment by reiddraper** [comment]
+1 from me as well.

**Pull request merged**
