### PR TITLE
ORSet V2

### PR DESCRIPTION
**Pull request by lenary**
Gave it a bit of attention to make it more concise and it should also have a smaller size when serialised. :)

EDIT: It seems work has been done on VVORSet, so not touching that.

### CODE REVIEW

**Comment by lenary** [comment]
As we've not yet deployed any OR-Set implementations (unless I'm wrong about this) I don't think upgrade/downgrade functions are needed.

**Comment by russelldb** [comment]
You are not wrong, no OR-Set in the wild.

**Comment by lenary** [comment]
Ah yes, I'm now reminded that @russelldb did some work on benchmarking this OR-Set. The bm was slightly biased towards a test that vvorset would do better at, so there wasn't much of an improvement, however, i think this OR-Set will do better when there are lots of keys and few adds/removes per key.

**Comment by russelldb** [comment]
Yeah, you could add some less biased scenarios to orset-bm.

**Comment by seancribbs** [comment]
Be sure you include all the callbacks.

**Pull request closed without merging**
